{{- if .Values.monitoring.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ include "cloudflare-gateway.name" . }}
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: {{ include "cloudflare-gateway.name" . }}
  name: {{ .Values.rbac.proxy.clusterRoleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.proxy.clusterRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudflare-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
