{{- if .Values.monitoring.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ include "cloudflare-gateway.name" . }}
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: {{ include "cloudflare-gateway.name" . }}
  name: {{ .Values.rbac.proxy.clusterRoleName }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}
