apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ include "cloudflare-gateway.name" . }}
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: {{ include "cloudflare-gateway.name" . }}
  name: {{ .Values.rbac.leaderElection.roleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.leaderElection.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudflare-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

