{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflare-gateway.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ include "cloudflare-gateway.name" . }}
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: {{ include "cloudflare-gateway.name" . }}
    {{- include "cloudflare-gateway.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
