{{- if .Values.monitoring.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ include "cloudflare-gateway.name" . }}
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: {{ include "cloudflare-gateway.name" . }}
    control-plane: controller-manager
  name: cloudflare-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
{{- end }}
